### ISSUE TITLE
Unsafe use of concurrent state

### ISSUE THREAD

**Issue by z64** [Blacksmoke16/athena#15]
Currently, use of `@@request` (and similar) is not safe across concurrent requests and can be exploited relatively easily. Please see the commit below for further details and a sample test:

https://github.com/z64/athena/commit/fad7f6b9574a026ab66f32f7a9c1ce6b26341a37

You'll need to think of another approach that doesn't involve sharing data between fibers like this. I don't have any suggestions at the moment as I'm wholly unfamiliar with Athena's design; I just noticed this issue in the code and thought I would bring it up, because it can cause some nasty bugs in user code that you might not even notice.

**Comment by Blacksmoke16** [comment]
❤️ Perfect thanks for the sample.  

One solution I think would be to pass the request context _into_ each action handler, but only if they defined a `ctx` argument.  This would be less clean imo than `get_request`, but it would (i think?) solve this issue, as each action handler would get the server context for _that_ specific request.

**Comment by Blacksmoke16** [comment]
@z64 Another idea i been toying around with would be making controller actions be instance methods instead of class methods. 

This would allow for each request to new up the controller, set the request/response behind the scenes, then expose instance `get_request/response` methods.

I think I would rather do that than having `ctx` be an action argument, but would depend on what i can get working.  I'll see how it goes.

**Comment by Blacksmoke16** [comment]
I went with option 2 and changed actions to be instance methods.  When a request is received, Athena will new up the corresponding class, passing the `HTTP::Server::Context` as a constructor argument.  This allows each request to have its own controller instance, thus isolating each request and allowing full concurrency support.
 
The `get_request` and `get_response` methods are now also instance methods and work just the same as they did.

The `handle_exception` method is still a class method, and now accepts the server context instead of the action method string.

Controllers are now class based since inheritance wouldn't work with structs due to the fact you cant inherit from a non abstract struct, which could not be instantiated for actions.

**Comment by z64** [comment]
I don't have an Athena project to check this with - I just ran your spec suite while investigating - but I see you incorporated my original spec. So that's good enough for me! Hopefully this will help you identify similar unsafe conditions in the future :cat:

**Comment by Blacksmoke16** [comment]
Yea for sure, can never have too much test coverage :P

Thanks for the issue.
